### ISSUE TITLE
Could not find a suitable TLS CA certificate bundle

### ISSUE THREAD

**Issue by relu** [bitnami/bitnami-docker-elasticsearch-curator#2]
Looks like the newer versions of this image are failing due to the following error:

```
ERROR     HTTP N/A error: Could not find a suitable TLS CA certificate bundle, invalid path: /opt/bitnami/python/lib/python3.6/site-packages/certifi/cacert.pem
```

Version: **5.3.8**

**Comment by dani8art** [comment]
Hi @relu,

Could you share any env var or configuration file that you were using so we can try to reproduce it locally?

Thanks!

**Comment by relu** [comment]
Hello! Here's the configuration I'm using from terraform:
```
"curator.yml" = <<-EOT
      ---                      
      client:                                              
        hosts:                                                                                                                 
          - ${var.logs_elasticsearch_domain_endpoint}
        port: 443           
        use_ssl: True                
        timeout: 30                    
        master_only: False
                                                               
      logging:
        loglevel: INFO
        logfile:             
        logformat: default
        blacklist: ['elasticsearch', 'urllib3']                                                                                
    EOT        
                                                               
    "actions.yml" = <<-EOT
      ---
      actions:
        1:
          action: delete_indices
          description: >-
            Delete indices older than ${local.curator_ttl_days} days (based on index name), for
            logstash- prefixed indices. Ignore the error if the filter does not
            result in an actionable list of indices (ignore_empty_list) and
            exit cleanly.
          options:
            ignore_empty_list: True
            timeout_override:
            continue_if_exception: False
            disable_action: False
          filters:
          - filtertype: pattern
            kind: prefix
            value: kubernetes-
            exclude:
          - filtertype: age
            source: name
            direction: older
            timestring: '%Y.%m.%d'
            unit: days
            unit_count: ${local.curator_ttl_days}
            exclude:
    EOT
```

Running with: `["/config/actions.yml", "--config", "/config/curator.yml"]`

There are no custom environment variables used.

Note that the elasticsearch cluster is an AWS ElasticSearch provisioned one. Hope this helps. Thanks!
