### ISSUE TITLE
Passing configuration file to container

### ISSUE THREAD

**Issue by stefanDeveloper** [bitnami/bitnami-docker-elasticsearch-curator#6]
Currently, I'm working on my `docker-compose` and struggled where I should mount the `curator.yml` as described in [curator documentation](https://www.elastic.co/guide/en/elasticsearch/client/curator/current/configfile.html). I found out that the following definition does not works for me.

```yml
  curator:
    image: bitnami/elasticsearch-curator:5.8.4
    volumes: 
      - ./curator/curator.yml:/.curator/curator.yml
    command:
      - "/.curator/curator.yml"
```

Maybe it is a good point to add it to the readme file to help new users getting started with it?

**Comment by stefanDeveloper** [comment]
I found out how to mount the configuration correctly:

```yml
    curator:
      image: bitnami/elasticsearch-curator:5.8.4
    volumes: 
      - ./curator/curator.yml:/.curator/curator.yml
      - ./curator/action.yml:/curator/.curator/action.yml
    command: 
      - "/curator/.curator/action.yml"
```
